id: P009408
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W20241
  title: བོད་ཀྱི་ལོ་རྒྱུས་དཔེ་ཐོ
  author: ''
  volumes:
    4f0e22ec8aff4c71bef0edf026576fcb:
      image_group_id: I1PD334
      title: ''
      volume_number: 1
      total_pages: 550
      base_file: v001.txt
